import uuid from 'uuid';

export default [
  {
    id: uuid(),
    title: '可燃ごみ',
    estimate: 5,
    startTime: '08:00',
    endTime: '08:05',
    memo: '衣類も可能',
  },
  {
    id: uuid(),
    title: 'メールチェック',
    estimate: 5,
    startTime: '10:17',
    endTime: '10:20',
    memo: '',
  },
  {
    id: uuid(),
    title: '予定表のチェック',
    estimate: 5,
    startTime: '10:17',
    endTime: '10:20',
    memo: '',
  },
  {
    id: uuid(),
    title: '日報',
    estimate: 10,
    startTime: '10:21',
    endTime: '10:32',
    memo: '',
  },
  {
    id: uuid(),
    title: '勤怠入力',
    estimate: 3,
    startTime: '10:52',
    endTime: '10:52',
    memo: '',
  },
  {
    id: uuid(),
    title: '朝会',
    estimate: 15,
    startTime: '11:10',
    endTime: '11:25',
    memo: '',
  },
  {
    id: uuid(),
    title: '#123 の対応',
    estimate: 20,
    startTime: '11:55',
    endTime: '12:13',
    memo: '',
  },
  {
    id: uuid(),
    title: '昼飯',
    estimate: 60,
    startTime: '13:00',
    endTime: '14:00',
    memo: '',
  },
  {
    id: uuid(),
    title: '開発MTG',
    estimate: 60,
    startTime: '14:00',
    endTime: '15:40',
    memo: '',
  },
  {
    id: uuid(),
    title: 'コードレビュー',
    estimate: 40,
    startTime: '18:00',
    endTime: '',
    memo: 'feature/issue01',
  },
];
