export default {
  CONTACTURL: 'https://docs.google.com/forms/d/e/1FAIpQLSd12kJ8lJ79_669Ymzx8QyRksfZ0LvmwasK99Ual7HdUOvNVg/viewform',
  REPOSITORYURL: 'https://github.com/hand-dot/taskchute-web',
  APPWIDTH: window.innerWidth,
  KEYEVENT_DELAY: 100,
  RENDER_DELAY: 1000,
  shortcuts: {
    HELP: 191,
    NEXTDATE: 190,
    PREVDATE: 188,
    SAVE: 83,
    INSERT: 73,
    TOGGLE_DASHBOAD: 74,
    TOGGLE_TASKPOOL: 75,
    SELECT_TABLE: 76,
    HOT_CURRENTTIME: 186,
  },
  menuItemKey: {
    DESCRIPTION: 'description',
    CONTACT: 'contact',
    GIT: 'git',
  },
  taskPoolType: {
    HIGHPRIORITY: 'highPriorityTasks',
    LOWPRIORITY: 'lowPriorityTasks',
    REGULAR: 'regularTasks',
    DAILY: 'dailyTasks',
  },
  taskPoolActionType: {
    ADD: 'add',
    EDIT: 'edit',
    MOVE: 'move',
    REMOVE: 'remove',
    DOWN: 'down',
    UP: 'up',
  },
  DATEFMT: 'YYYY-MM-DD',
  INITIALDATE: '1970-01-01',
};
